version: "3"

services:
  # rdbms:
  #   image: postgres:12
  #   env_file:
  #     - .env.development
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=${DB_DATABASE}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   ports:
  #     - ${DB_OUTER_PORT}:${DB_INNER_PORT}
  #   networks:
  #     - public
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - client-node-modules:/app/node_modules
    networks:
      - public
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    # ports:
    #   - ${API_SERVER_PORT}:${API_SERVER_PORT}
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    networks:
      - public
    # depends_on:
    #   - rdbms

volumes:
  # db-data:
  client-node-modules:
  backend-node-modules:

networks:
  public:
    driver: bridge
